FROM node:9.6.1-slim

ENV PATH $PATH:/usr/src/app/node_modules/.bin

WORKDIR /usr/src/app

# Install pm2
RUN npm config set unsafe-perm tru
RUN npm install pm2 -g

# Install dependencies
COPY ./package.json ./
RUN npm install

# Copy source files
COPY . .

# Build application
RUN npm run build

EXPOSE 4000

CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]
